services:
  - type: web
    name: blog-app-docker
    runtime: docker # phpではなくdockerに戻します
    plan: free
    envVars:
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: APP_KEY
        value: base64:dLio5Vy1a2mCAdod7jCNX7T/DtWBB2oFv2KCbUsL01U=